version: '3'
services:
  pisignage-server:
    image: pisignage/pisignage-server:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - media:/media
      - data:/data

volumes:
  media:
  data:
